version: 2.1

jobs:
  lint:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.9
        auth:
          username: axsch
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:12
        auth:
          username: axsch
          password: $DOCKERHUB_PASSWORD
        environment:
          DATABASE_URL: $DATABASE_URL
          PIPENV_VENV_IN_PROJECT: "true"
          POSTGRES_USER: postgres
          POSTGRES_DB: rooneyMc
          SECRET_KEY: $SECRET_KEY
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.9/site-packages
