version: 2.1

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.9
        auth:
          username: axsch
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:12
        auth:
          username: axsch
          password: $DOCKERHUB_PASSWORD
        environment:
          DATABASE_URL: $DATABASE_URL
          PIPENV_VENV_IN_PROJECT: "true"
          POSTGRES_USER: root
          POSTGRES_DB: rooneyMc
          SECRET_KEY: $SECRET_KEY
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.9/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --three
          name: Build
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.9/site-packages"
      - run:
          command: |
            pipenv run python ./backend/manage.py test
          name: Tests
